In [1]:
import pandas as pd

In [2]:
# creating two dataframes. The data inputs were changed after January 2021 and each dataframe will need to be manipulated to merge them together. 
df = pd.concat(
    map(pd.read_csv, 
    [
    '2019\JC-201901-citibike-tripdata.csv', 
    '2019\JC-201902-citibike-tripdata.csv',
    '2019\JC-201903-citibike-tripdata.csv', 
    '2019\JC-201904-citibike-tripdata.csv', 
    '2019\JC-201905-citibike-tripdata.csv', 
    '2019\JC-201906-citibike-tripdata.csv', 
    '2019\JC-201907-citibike-tripdata.csv', 
    '2019\JC-201908-citibike-tripdata.csv', 
    '2019\JC-201909-citibike-tripdata.csv', 
    '2019\JC-201910-citibike-tripdata.csv',
    '2019\JC-201911-citibike-tripdata.csv', 
    '2019\JC-201912-citibike-tripdata.csv',   
    '2020\JC-202001-citibike-tripdata.csv', 
    '2020\JC-202002-citibike-tripdata.csv',
    '2020\JC-202003-citibike-tripdata.csv', 
    '2020\JC-202004-citibike-tripdata.csv', 
    '2020\JC-202005-citibike-tripdata.csv', 
    '2020\JC-202006-citibike-tripdata.csv', 
    '2020\JC-202007-citibike-tripdata.csv', 
    '2020\JC-202008-citibike-tripdata.csv', 
    '2020\JC-202009-citibike-tripdata.csv', 
    '2020\JC-202010-citibike-tripdata.csv',
    '2020\JC-202011-citibike-tripdata.csv', 
    '2020\JC-202012-citibike-tripdata.csv', 
    '2021\JC-202101-citibike-tripdata.csv', 
    ]), ignore_index=True)

df1 = pd.concat(
    map(pd.read_csv, 
    [
    '2021\JC-202102-citibike-tripdata.csv',
    '2021\JC-202103-citibike-tripdata.csv', 
    '2021\JC-202104-citibike-tripdata.csv', 
    '2021\JC-202105-citibike-tripdata.csv', 
    '2021\JC-202106-citibike-tripdata.csv', 
    '2021\JC-202107-citibike-tripdata.csv', 
    '2021\JC-202108-citibike-tripdata.csv', 
    '2021\JC-202109-citibike-tripdata.csv', 
    '2021\JC-202110-citibike-tripdata.csv',
    '2021\JC-202111-citibike-tripdata.csv', 
    '2021\JC-202112-citibike-tripdata.csv',
    '2022\JC-202201-citibike-tripdata.csv', 
    '2022\JC-202202-citibike-tripdata.csv',
    '2022\JC-202203-citibike-tripdata.csv', 
    '2022\JC-202204-citibike-tripdata.csv', 
    '2022\JC-202205-citibike-tripdata.csv', 
    '2022\JC-202206-citibike-tripdata.csv', 
    '2022\JC-202207-citibike-tripdata.csv', 
    '2022\JC-202208-citibike-tripdata.csv', 
    '2022\JC-202209-citibike-tripdata.csv', 
    '2022\JC-202210-citibike-tripdata.csv',
    '2022\JC-202211-citibike-tripdata.csv', 
    '2022\JC-202212-citibike-tripdata.csv',
    ]), ignore_index=True)

In [3]:
df_reduced = df[['start station name','start station latitude','start station longitude','starttime','end station name','end station latitude', 'end station longitude','stoptime','usertype']]

In [4]:
df1_reduced = df1[['start_station_name','start_lat','start_lng','started_at','end_station_name','end_lat','end_lng','ended_at','member_casual']]

In [5]:
#changing the names as a personal preference. 

df_rename = df_reduced.rename(columns={'start station name':'start_station_name','start station latitude':'start_lat','start station longitude':'start_lng','starttime':'ride_time_start','end station name':'end_station_name', 'end station latitude':'end_lat','end station longitude':'end_lng','stoptime':'ride_time_end', 'usertype':'usertype'})

In [6]:
#changing the names as a personal preference. 
df1_rename = df1_reduced.rename(columns={'start_station_name':'start_station_name','start_lat':'start_lat','start_lng':'start_lng','started_at':'ride_time_start','end_station_name':'end_station_name', 'end_lat':'end_lat','end_lng':'end_lng','ended_at':'ride_time_end', 'member_casual':'usertype'})

In [7]:
#Using concat to combine the two dataframes together instead of trying to merge. 
df2 = pd.concat([df_rename, df1_rename], ignore_index=True)

In [8]:
#the ride_time_start and ride_time_end were objects and I'm using pd.to_datetime to convert them to a datetime. 
df2['ride_time_start'] = pd.to_datetime(df2['ride_time_start'])
df2['ride_time_end'] = pd.to_datetime(df2['ride_time_end'])

In [9]:
#CitiBike changed the name of the users from member and I'm converting all the names to my preferred title of Subscriber and Cusrtomer 
df2['usertype'] = df2['usertype'].replace(['member', 'casual'], ['Subscriber', 'Customer'])

In [10]:
#The data is missing some coordinates and station locations and I'm removing those enteries before exporting dataframe to a csv file. 
df3 = df2.dropna()

In [11]:
#calculating the ride time that will be used to determine how much time a a subscribing user rides vs a one-time customer. 
df3['ride_time_min'] =  df3['ride_time_end'] - df3['ride_time_start']
df3['ride_time_min'] = df3['ride_time_min'].dt.total_seconds().div(60).astype(int)
df3

c:\Users\erdos\anaconda3\envs\PythonDataOne\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

c:\Users\erdos\anaconda3\envs\PythonDataOne\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,start_station_name,start_lat,start_lng,ride_time_start,end_station_name,end_lat,end_lng,ride_time_end,usertype,ride_time_min
0,Exchange Place,40.716247,-74.033459,2019-01-01 03:09:09.711,Essex Light Rail,40.712774,-74.036486,2019-01-01 03:12:30.879,Subscriber,3
1,Exchange Place,40.716247,-74.033459,2019-01-01 05:18:00.106,Washington St,40.724294,-74.035483,2019-01-01 05:26:25.905,Subscriber,8
2,Exchange Place,40.716247,-74.033459,2019-01-01 10:36:33.340,Liberty Light Rail,40.711242,-74.055701,2019-01-01 10:49:10.260,Subscriber,12
3,Exchange Place,40.716247,-74.033459,2019-01-01 12:43:38.643,Washington St,40.724294,-74.035483,2019-01-01 13:09:54.528,Customer,26
4,Exchange Place,40.716247,-74.033459,2019-01-01 12:43:39.601,Washington St,40.724294,-74.035483,2019-01-01 13:09:46.510,Customer,26
...,...,...,...,...,...,...,...,...,...,...
2281672,Dey St,40.737828,-74.067083,2022-12-06 15:43:38.000,Riverview Park,40.744319,-74.043991,2022-12-06 15:53:57.000,Subscriber,10
2281673,9 St HBLR - Jackson St & 8 St,40.747907,-74.038412,2022-12-08 08:17:51.000,City Hall - Washington St & 1 St,40.737360,-74.030970,2022-12-08 08:23:33.000,Customer,5
2281674,Mama Johnson Field - 4 St & Jackson St,40.743140,-74.040041,2022-12-23 14:10:07.000,City Hall - Washington St & 1 St,40.737360,-74.030970,2022-12-23 14:14:18.000,Subscriber,4
2281675,Mama Johnson Field - 4 St & Jackson St,40.743135,-74.040080,2022-12-02 04:43:25.000,City Hall - Washington St & 1 St,40.737360,-74.030970,2022-12-02 04:46:55.000,Subscriber,3
2281676,14 St Ferry - 14 St & Shipyard Ln,40.752747,-74.024035,2022-12-30 14:50:17.000,City Hall - Washington St & 1 St,40.737360,-74.030970,2022-12-30 14:55:37.000,Subscriber,5

In [12]:
#removing outliers that would skew the ride time data. 
index_ride_min = df3[ (df3['ride_time_min'] >= 180) | (df3['ride_time_min'] <= 2) ].index
df3.drop(index_ride_min , inplace=True)
df3

c:\Users\erdos\anaconda3\envs\PythonDataOne\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,start_station_name,start_lat,start_lng,ride_time_start,end_station_name,end_lat,end_lng,ride_time_end,usertype,ride_time_min
0,Exchange Place,40.716247,-74.033459,2019-01-01 03:09:09.711,Essex Light Rail,40.712774,-74.036486,2019-01-01 03:12:30.879,Subscriber,3
1,Exchange Place,40.716247,-74.033459,2019-01-01 05:18:00.106,Washington St,40.724294,-74.035483,2019-01-01 05:26:25.905,Subscriber,8
2,Exchange Place,40.716247,-74.033459,2019-01-01 10:36:33.340,Liberty Light Rail,40.711242,-74.055701,2019-01-01 10:49:10.260,Subscriber,12
3,Exchange Place,40.716247,-74.033459,2019-01-01 12:43:38.643,Washington St,40.724294,-74.035483,2019-01-01 13:09:54.528,Customer,26
4,Exchange Place,40.716247,-74.033459,2019-01-01 12:43:39.601,Washington St,40.724294,-74.035483,2019-01-01 13:09:46.510,Customer,26
...,...,...,...,...,...,...,...,...,...,...
2281672,Dey St,40.737828,-74.067083,2022-12-06 15:43:38.000,Riverview Park,40.744319,-74.043991,2022-12-06 15:53:57.000,Subscriber,10
2281673,9 St HBLR - Jackson St & 8 St,40.747907,-74.038412,2022-12-08 08:17:51.000,City Hall - Washington St & 1 St,40.737360,-74.030970,2022-12-08 08:23:33.000,Customer,5
2281674,Mama Johnson Field - 4 St & Jackson St,40.743140,-74.040041,2022-12-23 14:10:07.000,City Hall - Washington St & 1 St,40.737360,-74.030970,2022-12-23 14:14:18.000,Subscriber,4
2281675,Mama Johnson Field - 4 St & Jackson St,40.743135,-74.040080,2022-12-02 04:43:25.000,City Hall - Washington St & 1 St,40.737360,-74.030970,2022-12-02 04:46:55.000,Subscriber,3
2281676,14 St Ferry - 14 St & Shipyard Ln,40.752747,-74.024035,2022-12-30 14:50:17.000,City Hall - Washington St & 1 St,40.737360,-74.030970,2022-12-30 14:55:37.000,Subscriber,5

In [13]:
#creating a helper column that will be used to calculate the total trips by particular paremeters in Tableau. 
df3 = df3.assign(trip_count=1)

In [15]:
#Creating a sample size and sorting the values by the ride start time that will be used to create the initial visuals in Tableau. Using the full dataset causes performance issues and slows down the development time. 

df_sample = df3.head(50000)
df_sample.to_csv('citibiketripsSample.csv')

In [16]:
#final tranformed dataframe that will be loaded into a CSV and imported into Tableau to create a viz. 

df3.to_csv('citibiketrips19-22.csv')